package com.usermgmt.usermgmtsystem.user;

import jakarta.persistence.*;

// Marks this class as a JPA entity, meaning it maps to a table in the database
@Entity
// Specifies that this entity maps to a table called "users" in the database
@Table(name = "users")
public class User {

    // Marks this field as the primary key for the table
    @Id
    // Specifies that the ID should be automatically generated by the database
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    // Maps this field to a column named "name" in the "users" table
    @Column(name = "name")
    private String name;

    // Maps this field to a column named "email" in the "users" table
    @Column(name = "email")
    private String email;

    // Maps this field to a column named "age" in the "users" table
    @Column(name = "age")
    private int age;

    // Maps this field to a column named "position" in the "users" table
    @Column(name = "position")
    private String position;

    // Maps this field to a column named "salary" in the "users" table
    @Column(name = "salary")
    private long salary;

    // Maps this field to a column named "file_URL" in the "users" table
    @Column(name = "file_URL")
    private String fileURL;

    // Add version field for optimistic locking
    @Version
    private Long version = 0L; // Initialize with default value

    // Getter method for the "id" field
    public Long getId() {
        return id;
    }

    // Setter method for the "id" field
    public void setId(Long id) {
        this.id = id;
    }

    // Getter method for the "name" field
    public String getName() {
        return name;
    }

    // Setter method for the "name" field
    public void setName(String name) {
        this.name = name;
    }

    // Getter method for the "email" field
    public String getEmail() {
        return email;
    }

    // Setter method for the "email" field
    public void setEmail(String email) {
        this.email = email;
    }

    // Getter method for the "age" field
    public int getAge() {
        return age;
    }

    // Setter method for the "age" field
    public void setAge(int age) {
        this.age = age;
    }

    // Getter method for the "position" field
    public String getPosition() {
        return position;
    }

    // Setter method for the "position" field
    public void setPosition(String position) {
        this.position = position;
    }

    // Getter method for the "salary" field
    public long getSalary() {
        return salary;
    }

    // Setter method for the "salary" field
    public void setSalary(long salary) {
        this.salary = salary;
    }

    // Getter method for the "publicURL" field
    public String getFileURL() {
        return fileURL;
    }

    // Setter method for the "publicURL" field
    public void setFileURL(String fileURL) {
        this.fileURL = fileURL;
    }

    // Getter method for the "version" field
    public Long getVersion() {
        return version;
    }

    // Setter method for the "version" field
    public void setVersion(Long version) {
        this.version = version;
    }
}
